---
# tasks file for roles/lighthause
- name: Install git
  become: true
  ansible.builtin.apt:
    name: git
    state: present

- name: LIGHTHOUSE | Get from git
  ansible.builtin.git:
    repo: "{{ lighthouse.source }}"
    version: master
    dest: "{{ lighthouse.dir }}"
  become: true

- name: LIGHTHOUSE | Remove default nginx config
  ansible.builtin.file:
    path: /etc/nginx/sites-enabled/default
    state: absent
  become: true

- name: LIGHTHOUSE | Create web config
  become: true
  ansible.builtin.template:
    src: lighthouse.j2
    dest: /etc/nginx/conf.d/default.conf
    mode: "0644"
  notify: NGINX | Restarted service
